baseURL = "http://bluzky.github.io"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Bluz is Orange"
theme = "journal"	
disqusShortname = "dan-van-phong-4.0"
googleAnalytics = "UA-40665301-3"

paginate = 7
canonifyurls = true


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"


 [author]
   name = "Dũng Nguyễn"
   bio = "Super hero"
   job = "Web developer"
   location = "Hồ Chí Minh, Việt Nam"
   # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
   # Your profile picture
   # Overwritten by your gravatar image if `author.gravatarEmail` is filled
   picture = "https://avatars3.githubusercontent.com/u/6194779?s=460&v=4"
   # Your Twitter username without the @. E.g : thibaudlepretre
   # twitter = "thibaudlepretre"
   # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
   # googlePlus = "+ThibaudLepretre"

  [[menu.main]]
      name = "#projects"
      url = "page/projects/"
      weight = 0
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
			
  [[menu.main]]
      name = "#blog"
      url = ""
      weight = 1
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"

  [[menu.main]]
      name = "#elixir"
      url = "/tags/elixir"
      weight = 2
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tag\"></i>"

  [[menu.main]]
      name = "#til"
      url = "/tags/til"
      weight = 3
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tag\"></i>"
			
  [[menu.main]]
      name = "#all-tags"
      url = "/tags"
      weight = 4
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
			
			
	[[menu.main]]
		  name = "#about"
		  url = "page/about/"
		  weight = 5
			pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"

			
	[[menu.links]]
	  weight = 1
	  identifier = "github"
	  name = "GitHub"
	  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
	  url = "https://github.com/bluzky"
		
		
	[params]
	  htmlTitle = "<span class='text-blue'>Bluz</span> is <span class='text-orange'>Orange</span>"
