baseURL = "http://bluzky.github.io"
languageCode = "en-us"
title = "The 54 tribes"
theme = "hugo"
#disqusShortname = "XXX"
googleAnalytics = "UA-40665301-3"


[Params]
    Subtitle = "technology tribal code force"
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
  #  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

  #[[Params.bigimg]]
  #  src = "img/triangle.jpg"
  #  desc = "Triangle"
  #[[Params.bigimg]]
  #  src = "img/sphere.jpg"
  #  desc = "Sphere"
  #  # position: see values of CSS background-position.
  #  position = "center top"
  #[[Params.bigimg]]
  #  src = "img/hexagon.jpg"
  #  desc = "Hexagon"

  [Author]
    name = "Dũng Nguyễn"
    website = "yourwebsite.com"
    email = "bluesky.1289@gmail.com"
   # facebook = "username"
   # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
    github = "bluzky"
   # gitlab = "username"
    twitter = "Dzung1289"
   # reddit = "username"
    linkedin = "dung-nguyen-tien-695ba135"
    # xing = "username"
    # stackoverflow = "users/XXXXXXX/username"
    # snapchat = "username"
    # instagram = "username"
    # youtube = "user/username" # or channel/channelname
    # soundcloud = "username"
    # spotify = "username"
    # bandcamp = "username"
    # itchio = "username"
    # vk = "username"
    # paypal = "username"
    # telegram = "username"

  [[menu.main]]
      name = "Blog"
      url = ""
      weight = 1

  [[menu.main]]
      name = "About"
      url = "page/about/"
      weight = 3

  [[menu.main]]
      identifier = "tags"
      name = "#tags"
      weight = 2

  [[menu.main]]
      parent = "tags"
      name = "#python"
      url = "/tags/python"
      weight = 1

  [[menu.main]]
      parent = "tags"
      name = "#elixir"
      url = "/tags/elixir"
      weight = 2

  [[menu.main]]
      parent = "tags"
      name = "#js"
      url = "/tags/javascript"
      weight = 3

  [[menu.main]]
      parent = "tags"
      name = "#go"
      url = "/tags/golang"
      weight = 4

  [[menu.main]]
      parent = "tags"
      name = "#til"
      url = "/tags/til"
      weight = 4

  [[menu.main]]
      parent = "tags"
      name = "All tags"
      url = "tags"
      weight = 5
